### ISSUE TITLE
KDE plasma 6 broke script

### ISSUE THREAD

**Issue by krunkske** [micha4w/kde-alt-f4-desktop#1]
basically the title. It just wont work anymore for plasma 6.

**Comment by benbc7** [comment]
I forked this repo and fixed it for plasma 6 [here](https://github.com/benbc7/kde-alt-f4-desktop). The changes break plasma 5 compatibility so I wasn't sure if I should make a PR yet.

**Comment by krunkske** [comment]
> I forked this repo and fixed it for plasma 6 [here](https://github.com/benbc7/kde-alt-f4-desktop). The changes break plasma 5 compatibility so I wasn't sure if I should make a PR yet.

I can't seem to find it in the KDE store. is that intentional or do I need to install the script myself. If so, how do I do that?

**Comment by benbc7** [comment]
I hadn't changed that part from the original. The KDE store only has the plasma 5 version, you'll have to clone it and run `kpackagetool6 --type=KWin/Script -i kde-alt-f4-desktop`

**Comment by micha4w** [comment]
Ye I noticed aswell, but ive had too much to do and so have been procrastinating it...

> I forked this repo and fixed it for plasma 6 [here](https://github.com/benbc7/kde-alt-f4-desktop). The changes break plasma 5 compatibility so I wasn't sure if I should make a PR yet.

Feel free to make a PR! I made a branch for Plasma 5 backwards compatibility, just in case.

**Comment by krunkske** [comment]
> I hadn't changed that part from the original. The KDE store only has the plasma 5 version, you'll have to clone it and run `kpackagetool6 --type=KWin/Script -i kde-alt-f4-desktop`

I'm sorry, I may be stupid but when i run that command in the source directory (the directory with the metatdata.json file) the command just spits out this:
 ```
Error: Installation of  failed: No such file: 
```

**Comment by benbc7** [comment]
> > I hadn't changed that part from the original. The KDE store only has the plasma 5 version, you'll have to clone it and run `kpackagetool6 --type=KWin/Script -i kde-alt-f4-desktop`
> 
> I'm sorry, I may be stupid but when i run that command in the source directory (the directory with the metatdata.json file) the command just spits out this:
> 
> ```
> Error: Installation of  failed: No such file: 
> ```

You actually want to run in on the parent folder, the folder that git creates when you clone it (kde-alt-f4-desktop).

**Comment by micha4w** [comment]
~The [store](https://store.kde.org/s/Opendesktop/p/2034030) should now have the Plasma6 version on it, if you install it from the KWin Scripts Settings menu, make sure to pick the v1.0.2 (Plasma 6) version!~

Edit: see the next comment

**Comment by micha4w** [comment]
Actually nvm me, I didn't see that there is now a Plasma 6 Section, it should now be on [here](https://www.pling.com/p/2138867)
