### ISSUE TITLE
Doesn't Work on Plasma 6..0.4

### ISSUE THREAD

**Issue by LechTheMitch** [micha4w/kde-alt-f4-desktop#3]
Tried to install  it from the KDE Store and directly from git and it doesn't work.

PSA: I have a weird panel configuration which might be linked to the issue.
![Uploading Screenshot_20240421_020957.png…]()

**Comment by micha4w** [comment]
Probably be the fault of bad Documentation. The extension doesn't edit the exisiting Alt-F4 shortcut, instead it creates a new Shortcut named `Close Window or show Logout Option`.

So make sure you do the following:
After installing the plugin, make sure its enable at `System Settings > Window Management > KWin Scripts`.
Go to `System Settings > Keyboard > Shortcuts > KWin` and set the Keyboard Shortcut `Close Window or show Logout Option`.

**Comment by LechTheMitch** [comment]
Thank you for clearing things up :)
