### ISSUE TITLE
The new plasma 6.1 update changed it so you can't choose all options when quitting plasma

### ISSUE THREAD

**Issue by WampireDev** [micha4w/kde-alt-f4-desktop#4]
I don't know if there is a way to bring that back but it would be nice if I could see all of the other options not just the shutdown and back button.

![Screenshot_20240618_181714](https://github.com/micha4w/kde-alt-f4-desktop/assets/118695291/a8a98c42-22db-45fa-941f-d312e84fee70)

**Comment by micha4w** [comment]
Isn't too hard to fix, but its a breaking change, and I'm not sure how to keep up backwards compatibility for plasma 6.0.

For now I've added a v1.0.3 file to the KWin store. And people need to chose themselves which file they want to install, not really clean though. I'll have to find a better way to this at some point.
